<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="shabi80" name="com.crm.qa.testcases.HomePageTest" tests="5" failures="1" timestamp="27 Feb 2018 18:07:32 GMT" time="90.640" errors="0">
  <testcase name="validatePageTitleTest" time="14.088" classname="com.crm.qa.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="Page Title does not mathch expected [CRMPRO] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]">
      <![CDATA[java.lang.AssertionError: Page Title does not mathch expected [CRMPRO] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.HomePageTest.validatePageTitleTest(HomePageTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validatePageTitleTest -->
  <testcase name="varifyUsernameTest" time="18.063" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="verifyContactsLink" time="20.561" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="verifyDealsLink" time="22.366" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="verifyTasksLink" time="15.562" classname="com.crm.qa.testcases.HomePageTest"/>
</testsuite> <!-- com.crm.qa.testcases.HomePageTest -->
